# Generated by Django 5.0.14 on 2026-06-24 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ticket_confirmation', 'Ticket Confirmation'), ('event_reminder', 'Event Reminder'), ('abandoned_cart', 'Abandoned Cart')], db_index=True, max_length=32)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['notification_type', 'target_type', 'target_id'], name='notif_type_target_idx'), models.Index(fields=['status', 'created_at'], name='notif_status_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(fields=('notification_type', 'target_type', 'target_id'), name='uniq_notifiaction_per_target'),
        ),
    ]
