# Generated by Django 5.0.14 on 2026-06-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
