# Generated by Django 5.0.14 on 2026-06-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerificatonToken',
            new_name='EmailVerificationToken',
        ),
    ]
