# Generated by Django 5.0.14 on 2026-06-09 16:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_remove_organization_update_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUIDv4). Set in Python before INSERT.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of row creation. Never writable.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last update. Managed by Django ORM.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. Rows with is_deleted=True are hidden from default queries.')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Auto-generated from title; unique enforced at DB level.', max_length=300, unique=True)),
                ('description', models.TextField()),
                ('banner', models.CharField(blank=True, default='', help_text='S3/R2 object key for the event banner image.', max_length=500)),
                ('venue', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 country code.', max_length=5)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('tickets_sold', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUIDv4). Set in Python before INSERT.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of row creation. Never writable.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last update. Managed by Django ORM.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. Rows with is_deleted=True are hidden from default queries.')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text="Ticket price in the org's configured currency. Use 0.00 for free tiers.", max_digits=10)),
                ('quantity', models.PositiveIntegerField(help_text='Total tickets available')),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('sale_start', models.DateTimeField(blank=True, null=True)),
                ('sale_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='events.event')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='even_search_vector_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['org', 'status'], name='event_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city', 'status'], name='event_city_status_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_datetime'], name='event_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettier',
            index=models.Index(fields=['event', 'is_active'], name='tier_event_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickettier',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='tier_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tickettier',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='tier_quantity_positive'),
        ),
    ]
