# Generated by Django 5.0.14 on 2026-06-18 18:10

import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUIDv4). Set in Python before INSERT.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of row creation. Never writable.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last update. Managed by Django ORM.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. Rows with is_deleted=True are hidden from default queries.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRM', 'confirm'), ('CANCELLED', 'cancelled'), ('REFUNDED', 'refunded')], db_index=True, default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Sum of all OrderItem subtotals. Snapshotted at creation.', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code.', max_length=3)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, default='', help_text='Payment provider reference. Populated in Phase 4.', max_length=225)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='PENDING order expiry timestamp. Null after confirm/cancel.', null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUIDv4). Set in Python before INSERT.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of row creation. Never writable.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last update. Managed by Django ORM.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. Rows with is_deleted=True are hidden from default queries.')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Tier price at time of purchase. Never updated.', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='events.tickettier')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier (UUIDv4). Set in Python before INSERT.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of row creation. Never writable.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last update. Managed by Django ORM.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. Rows with is_deleted=True are hidden from default queries.')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('USED', 'Used'), ('CANCELLED', 'Cancelled')], db_index=True, default='VALID', max_length=20)),
                ('qr_code', models.CharField(default=apps.orders.models.generate_qr_code, help_text='Unique token for QR code generation. UUIDv4 hex.', max_length=64, unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='Set when ticket is scanned at event entry (Phase 5).', null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.orderitem')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.tickettier')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['attendee', 'status'], name='order_attendee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event', 'status'], name='order_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expires_at'], name='order_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'tier'], name='orderitem_order_tier_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='orderitem_quantity_non_negative'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'status'], name='ticket_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['attendee', 'status'], name='ticket_attendee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['qr_code'], name='ticket_qr_code_idx'),
        ),
    ]
