# Generated by Django 5.0.14 on 2026-06-09 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='Action identifier, e.g. EVENT_CREATED, ORDER_CONFIRMED.', max_length=100)),
                ('entity_type', models.CharField(help_text="Model class name, e.g. 'Event', 'Order'.", max_length=100)),
                ('entity_id', models.CharField(help_text='Primary key of the affected entity (UUID as string).', max_length=255)),
                ('diff', models.JSONField(blank=True, help_text='Before/after state snapshot. Null for create actions.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['actor', 'created_at'], name='audit_logs_actor_i_5bd818_idx')],
            },
        ),
    ]
